services:
  kwtc_mysql_db:
    image: mysql:8
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'mysql --database=kwtc_dbo --password=password --execute="SELECT count(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B',
        ]
      interval: 30s
      timeout: 10s
      retries: 4
    command: --sql_mode="NO_ENGINE_SUBSTITUTION"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306