name: Release drafter

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  release-drafter:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: config/release-drafter-config.yml
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}